<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>GE</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div>
                        <h3>Status:</h3>
                        <?php if ($error) : ?>
                            <div class="alert alert-danger" role="alert">
                                <?= $mensage ?> 
                            </div>
                        <?php else :?>
                            <div class="alert alert-success" role="alert">
                                <?= $mensage ?>
                            </div>
                        <?php endif; ?>
                        <h4><a href="<?= $url_for ?>">HOME</a></h4>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>